apiVersion: v1
kind: Endpoints
metadata:
  name: dubbo-zookeeper

subsets:
- addresses:
  - ip: 192.168.100.3
  ports:
  - port: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-zookeeper
spec:
  ports:
  - port: 2181
